Changes to allow display from docker.

diff --git a/wvu_comp_final b/wvu_comp_final
--- a/wvu_comp_final
+++ b/wvu_comp_final
@@ -13,6 +13,7 @@ cd $_this_dir
 
 # Source helper scripts
 source "srcp2_setup.bash"
+source "gpu_and_x.bash"
 
 image_tag="wvu-competitor:latest"
 
@@ -184,11 +185,28 @@ echo
 
 #    $cmp_volumes \
 
+# X Server / Display 
+if ! x_host_setup; then
+    echo -e "$echo_error Host X-Server setup failed"
+    exit 1
+fi
+# XServer
+xsock="/tmp/.X11-unix"
+xauth="/tmp/.docker.xauth"
+echo -e "$echo_info X Display ${b}Setup Done${rs}"
+
 
 docker run --rm  \
     --name $cmp_container_name\
     --user 1001:1001 \
     $interactive \
+    --env="DISPLAY"=$DISPLAY \
+    --env=XAUTHORITY=$xauth \
+    --env=XAUTHORITY=$xauth \
+    --volume=$xsock:$xsock:rw \
+    --volume=$xauth:$xauth:rw \
+    --volume=/dev/log:/dev/log:rw \
+    --device=/dev/dri:/dev/dri \
     --network $srcp2net_name \
     --network-alias $simalias_name \
     --env=ROS_MASTER_URI="http://${simalias_name}:11311" \
